# Generated by Django 5.0.6 on 2024-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_Heading', models.CharField(max_length=50)),
                ('about_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_title', models.CharField(max_length=50)),
                ('social_link', models.URLField(max_length=500)),
            ],
        ),
    ]
