# Generated by Django 5.0.6 on 2024-06-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_Heading',
            new_name='about_heading',
        ),
    ]
