# Generated by Django 5.0.6 on 2024-06-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_about_heading_about_about_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_heading',
            new_name='about_Heading',
        ),
    ]
